name: Download Ubuntu 22.04 APT Packages

on:
  workflow_dispatch:
    inputs:
      start_letter:
        description: 'Start letter of package names to download'
        required: true
        default: 'a'
      end_letter:
        description: 'End letter of package names to download'
        required: true
        default: 'z'

jobs:
  apt-mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Set up repository
      run: sudo apt-get update

    - name: Install apt-mirror and grep
      run: sudo apt-get install -y apt-mirror grep

    - name: Create mirror directory
      run: |
        sudo mkdir -p /tmp/ubuntu-mirror
        sudo chown -R $USER:$USER /tmp/ubuntu-mirror

    - name: Generate package filter list
      run: |
        apt-cache pkgnames | grep '^[a-zA-Z]' > /tmp/package-list.txt
        awk -v start="${{ github.event.inputs.start_letter }}" -v end="${{ github.event.inputs.end_letter }}" \
        'tolower($0) ~ "^"start, tolower($0) ~ "^"end' /tmp/package-list.txt > /tmp/filter-list.txt
        wc -l  /tmp/filter-list.txt

    - name: Configure apt-mirror
      run: |
        echo "deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse" | sudo tee -a /etc/apt/mirror.list
        echo "deb-src http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse" | sudo tee -a /etc/apt/mirror.list
        echo "deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse" | sudo tee -a /etc/apt/mirror.list
        echo "deb-src http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse" | sudo tee -a /etc/apt/mirror.list
        echo "deb http://archive.ubuntu.com/ubuntu jammy-security main restricted universe multiverse" | sudo tee -a /etc/apt/mirror.list
        echo "deb-src http://archive.ubuntu.com/ubuntu jammy-security main restricted universe multiverse" | sudo tee -a /etc/apt/mirror.list
        echo "set base_path /tmp/ubuntu-mirror" | sudo tee -a /etc/apt/mirror.list
        echo "clean /tmp/ubuntu-mirror/var" | sudo tee -a /etc/apt/mirror.list
        echo "set run_postmirror 0" | sudo tee -a /etc/apt/mirror.list
        echo "set defaultarch amd64" | sudo tee -a /etc/apt/mirror.list
        cat /tmp/filter-list.txt | xargs -I {} echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse [{}]" > /tmp/ubuntu-mirror/mirror.list
        wc -l  /tmp/ubuntu-mirror/mirror.list

    - name: Run apt-mirror
      run: sudo apt-mirror

    - name: Upload mirror to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-mirror
        path: /tmp/ubuntu-mirror

    - name: Clean up
      run: sudo rm -rf /tmp/ubuntu-mirror
