name: Download&Package&Upload Hugging Face Model
on:
  workflow_dispatch:
    inputs:
      model_name:
        description: '请填写 Hugging Face 模型名称'
        required: true
        default: 'distilbert-base-uncased'  # 设置默认的 Hugging Face 模型名称

jobs:
  download_and_package:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install necessary tools
      run: |
        sudo apt-get update
        sudo apt-get install wget git-lfs zip

    - name: Get model files list without downloading large files
      run: |
        REPO_OWNER="huggingface"
        REPO_NAME="${{ github.event.inputs.model_name }}"
        BRANCH="main"
        
        curl -s "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/git/trees/$BRANCH?recursive=1" | jq -r '.tree[] | select(.type=="blob") | .path' >

    - name: Download files incrementally and handle capacity
      run: |
        model_name="${{ github.event.inputs.model_name }}"
        model_url="https://huggingface.co/${model_name}/resolve/main"
        model_dir="/mnt/model"
        tar_dir="tar_parts"
        mkdir -p $tar_dir
        part_size=20480  # 10GB in MB
        current_part=1
        current_size=0
        current_tar="${tar_dir}/${model_name}_part${current_part}.tar.gz"
        
        cat file_list.txt | while read file; do
            file_size=$(wget --spider "$model_url/$file" 2>&1 | grep Length | awk '{print $2}')
            new_size=$((current_size + file_size / 1048576))
            
            if [ $new_size -gt $part_size ]; then
                echo "Uploading part ${current_part}"
                gh api \
                  -X POST \
                  -F "file=@${current_tar}" \
                  -F "name=huggingface-model" \
                  -F "path=$current_tar"
                rm $current_tar
                
                current_part=$((current_part + 1))
                current_tar="${tar_dir}/${model_name}_part${current_part}.tar.gz"
                current_size=0
            fi
            
            wget -P $model_dir "$model_url/$file"
            tar -rvf - "$model_dir/$file" | gzip >> "$current_tar"
            current_size=$new_size
            rm -f "$model_dir/$file"
        done

    - name: Upload remaining artifact
      run: |
        gh api \
          -X POST \
          -F "file=@${current_tar}" \
          -F "name=huggingface-model" \
          -F "path=$current_tar"
