name: Download Ubuntu 22.04 APT Packages

on:
  workflow_dispatch:
    inputs:
      mirror_source:
        description: 'Mirror Source'
        required: true
        default: 'deb'
      mirror_url:
        description: 'Mirror URL'
        required: true
        default: 'http://archive.ubuntu.com/ubuntu'
      mirror_tag:
        description: 'Mirror Tag'
        required: true
        default: 'jammy main'
      letter_range:
        description: 'Letter Range'
        required: false
        default: 'a-g'

jobs:
  apt-mirror:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Set up repository
      run: sudo apt-get update

    - name: Install apt-mirror and grep
      run: sudo apt-get install -y apt-mirror grep

    - name: Create mirror directory
      run: |
        sudo mkdir -p /mnt/ubuntu-mirror
        sudo chown -R $USER:$USER /mnt/ubuntu-mirror
        sudo cp ./scripts/apt-mirror /usr/bin/apt-mirror
        sudo cat /usr/bin/apt-mirror

    - name: Configure apt-mirror
      run: |
        echo "${{ github.event.inputs.mirror_source }} ${{ github.event.inputs.mirror_url }} ${{ github.event.inputs.mirror_tag }}" | sudo tee /etc/apt/mirror.list
        echo "set base_path /mnt/ubuntu-mirror" | sudo tee -a /etc/apt/mirror.list
        echo "clean /mnt/ubuntu-mirror/var" | sudo tee -a /etc/apt/mirror.list
        echo "set run_postmirror 0" | sudo tee -a /etc/apt/mirror.list
        echo "set defaultarch amd64" | sudo tee -a /etc/apt/mirror.list
        echo "set package_range ${{ github.event.inputs.letter_range }}" | sudo tee -a /etc/apt/mirror.list
        wc -l /etc/apt/mirror.list

    - name: Run apt-mirror
      run: sudo apt-mirror

    - name: Upload mirror to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-mirror-${{ github.event.inputs.mirror_source }}-${{ github.event.inputs.mirror_tag }}
        path: /mnt/ubuntu-mirror

    - name: Clean up
      run: sudo rm -rf /mnt/ubuntu-mirror
