name: Download&Package&Upload Hugging Face Model
on:
  workflow_dispatch:
    inputs:
      model_name:
        description: '请填写 Hugging Face 模型名称'
        required: true
        default: 'distilbert-base-uncased'  # 设置默认的 Hugging Face 模型名称

jobs:
  download_and_package:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install necessary tools and Node.js packages
      run: |
        sudo apt-get update
        sudo apt-get install -y wget git-lfs zip jq
        npm install @actions/artifact

    - name: Get model files list without downloading large files
      run: |
        model_name="${{ github.event.inputs.model_name }}"
        repo_url="https://huggingface.co/${model_name}.git"
        GIT_LFS_SKIP_SMUDGE=1 git clone $repo_url repo
        cd repo
        git ls-tree -r HEAD --name-only > ../file_list.txt
        cd ..
        rm -rf repo

    - name: Create JavaScript script for uploading artifacts
      run: |
        echo "const { DefaultArtifactClient } = require('@actions/artifact');
        const artifactClient = new DefaultArtifactClient();
        const fs = require('fs');
        const { execSync } = require('child_process');

        const uploadArtifact = async (artifactName, filePath) => {
          await artifactClient.uploadArtifact(artifactName, [filePath], { retentionDays: 5 });
        };

        module.exports = { uploadArtifact };" > upload.js

    - name: Download files incrementally and handle capacity
      run: |
        model_name="${{ github.event.inputs.model_name }}"
        model_name_sanitized="${model_name//\//.}"
        model_url="https://huggingface.co/${model_name}/resolve/main"
        model_dir="/mnt/model"
        tar_dir="/mnt/tar_parts"
        sudo mkdir -p $tar_dir
        part_size=20480  # 20GB in MB
        current_part=1
        current_size=0
        current_tar="${tar_dir}/${model_name_sanitized}_part${current_part}.tar"
        
        cat file_list.txt | while read file; do
            file_size=$(sudo wget --spider "$model_url/$file" 2>&1 | grep Length | awk '{print $2}')
            file_size=${file_size:-0}  # Handle cases where file_size is empty
            new_size=$((current_size + file_size / 1048576))
            
            if [ $new_size -gt $part_size ]; then
                sudo tar -czvf "${current_tar}.gz" -C $(dirname "$current_tar") $(basename "$current_tar")
                sudo node -e "const { uploadArtifact } = require('./upload'); uploadArtifact('huggingface-model-${model_name_sanitized}-part${current_part}', '${current_tar}.gz')"
                sudo rm "${current_tar}.gz"
                
                current_part=$((current_part + 1))
                current_tar="${tar_dir}/${model_name_sanitized}_part${current_part}.tar"
                current_size=0
            fi
            
            sudo wget --progress=bar:force:noscroll -P $model_dir "$model_url/$file"
            filename=$(basename "$file")
            sudo tar -rvf "$current_tar" -C "$model_dir" "$filename"
            current_size=$new_size
            sudo rm -f "$model_dir/$filename"
        done
    
        sudo tar -czvf "${current_tar}.gz" -C $(dirname "$current_tar") $(basename "$current_tar")
        sudo node -e "const { uploadArtifact } = require('./upload'); uploadArtifact('huggingface-model-${model_name_sanitized}-part${current_part}', '${current_tar}.gz')"
        sudo rm "${current_tar}.gz"
      env:
        MODEL_NAME: ${{ github.event.inputs.model_name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
