name: Ollama Pull Model
on:
  workflow_dispatch:
    inputs:
      model_name:
        description: '请填写 Ollama 模型名称'
        required: true
        default: 'bge-m3'  # 设置默认的 Ollama 模型名称

jobs:
  download_and_package:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
       
    - name: Download ollama model
      run: |
        model_name="${{ github.event.inputs.model_name }}"
        ollama pull "${model_name}"
        
    - name: Package model
      run: |
        tar -czvf ${model_name}.tar.gz ./model

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ollama-model
        path: ${{ github.workspace }}/*.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天，最多可设置 90 天
