name: Setup Playwright

on:
  workflow_dispatch
      

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      

      - name: Install Playwright and dependencies
        run: |
          pip install playwright==1.51.0
          playwright install

      - name: Create cache archive
        run: |
          zip -r playwright_cache.zip ~/.cache/ms-playwright

      - name: Upload Docker images as release assets
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: playwright-cache
          files: playwright_cache.zip
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
